sudo: false

addons:
  apt:
    packages:
      - make
      - unrar
      - automake
      - libtool
      - gcc
      - g++
      - gperf
      - flex
      - bison
      - texinfo
      - gawk
      - ncurses-dev
      - libexpat-dev
      - python
      - python-serial
      - sed

language: c

before_script:
  - cd ..; wget 'https://github.com/m-thu/esp8266/blob/master/esp-open-sdk.tar.bz2?raw=true'; tar xjf esp-open-sdk.tar.bz2; cd ../esp8266
  - cd ..; git clone https://github.com/themadinventor/esptool.git; cd esp8266

script:
  - "make all"
