sudo: false

addons:
  apt:
    packages:
      - make
      - unrar
      - automake
      - libtool
      - gcc
      - g++
      - gperf
      - flex
      - bison
      - texinfo
      - gawk
      - ncurses-dev
      - libexpat-dev
      - python
      - python-serial
      - sed

language: c

before_script:
  - cd $HOME; echo $HOME; wget 'https://github.com/m-thu/esp8266/blob/master/esp-open-sdk.tar.bz2?raw=true' -O esp-open-sdk.tar.bz2; tar xjf esp-open-sdk.tar.bz2; cd $TRAVIS_BUILD_DIR; echo $TRAVIS_BUILD_DIR
  - cd $HOME; git clone https://github.com/themadinventor/esptool.git; cd $TRAVIS_BUILD_DIR

script:
  - "make all"
